#!/bin/sh

NEWTAG=$1
TAGS=$(git tag -l)

for t in $TAGS
do
    if [ $t = $NEWTAG ]
    then
        echo "⛔️ Tag $NEWTAG already exists!"
        exit 1
    fi
done

git checkout -b "release/$NEWTAG"

BRANCHNAME=$(git branch --show-current)

echo "created branch: $BRANCHNAME"

echo "import Foundation
// This is automatically generated by 'create-version.sh'

extension OJP {
    /// Current version of the SDK: $NEWTAG
    public static let version = \"$NEWTAG\"
}" > Sources/OJP/Generated/Version.swift

git commit -am "Create Version $NEWTAG"

git tag $NEWTAG

git push --tags --set-upstream origin $BRANCHNAME

open "https://github.com/openTdataCH/ojp-ios/compare/release/$NEWTAG?expand=1"
