# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: "Run Swift Package tests (Platform: macOS)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    -  cron: '0 12 * * 1-5'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1 # Xcode
      with:
        xcode-version: 'latest-stable'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
